# Colors
MENU_COLOR = "#1E1E1E"
CONTENT_COLOR = "#121212"
FEATURE_COLOR = "#8A2BE2"
ERROR_COLOR = "#FF0000"
GOOD_COLOR = "#017301"
FONT_COLOR = "#ababab"
SLIDER_COLOR = "#333333"
PRESS_COLOR = "#333333"

# Window Size
MIN_SIZE_W = 900
MIN_SIZE_H = 620
WINDOW_SIZE = f"{MIN_SIZE_W}x{MIN_SIZE_H}"

# Text & Font
FONT = "Fixedsys"
TEXT_JUSTIFY = "left"          
FONT_SIZE_CONTENT = 8
FONT_SIZE_OPTIONS = 8
FONT_SIZE_SUBTITLE = 10
FONT_SIZE_TITLE = 12
FONT_SIZE_BIG_TITLE = 20

# Others
WIDTH = 20
LENGTH = 175
CONTENT_PAD_Y = 10
CONTENT_PAD_X = 10
RELIEF_BASIC = "flat"
RELIEF_FANCY = "ridge"
RELIEF_FRAME = "sunken"
DEFAULT_PAGE = " ⚔️ Clicker"

# Tooltip
WAIT_TIME = 25
WRAP_LENGTH = 125

# Sidebar
SIDEBAR_WIDTH = 140
SIDEBAR_ITEM_H = 40
SIDEBAR_ACCENT_W = 3

# Status Bar
STATUS_BAR_H = 24
STATUS_PILL_PAD_X = 6
STATUS_PILL_PAD_Y = 2

# Card
CARD_CORNER_R = 4
CARD_PAD = 12

# Typography Scale
FONT_XS = 7
FONT_SM = 8
FONT_MD = 10
FONT_LG = 12
FONT_XL = 16
FONT_XXL = 20

# Accent Colors
ACCENT_COLOR = "#8A2BE2"
INACTIVE_COLOR = "#555555"
